apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: orh87/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: orh87/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: orh87/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/**/*.ts'
            dest: .
          - src: '/**/*.tsx'
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
